services:
  - type: web
    name: auth-service
    env: docker
    plan: free
    rootDir: MediBook/services/auth-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: appointment-service
    env: docker
    plan: free
    rootDir: MediBook/services/appointment-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: medical-record-service
    env: docker
    plan: free
    rootDir: MediBook/services/medical-record-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: notification-service
    env: docker
    plan: free
    rootDir: MediBook/services/notification-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: payment-service
    env: docker
    plan: free
    rootDir: MediBook/services/payment-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: provider-service
    env: docker
    plan: free
    rootDir: MediBook/services/provider-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: review-service
    env: docker
    plan: free
    rootDir: MediBook/services/review-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: schedule-service
    env: docker
    plan: free
    rootDir: MediBook/services/schedule-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"

  - type: web
    name: api-gateway
    env: docker
    plan: free
    rootDir: MediBook/services/api-gateway
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: Jwt__Issuer
        value: "MediBookAuthService"
      - key: Jwt__Audience
        value: "MediBookNetwork"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ServiceUrls__ApiGateway
        value: "https://api-gateway-vdad.onrender.com"
      - key: ServiceUrls__AuthService
        value: "https://auth-service-ij1y.onrender.com/"
      - key: ServiceUrls__ProviderService
        value: "https://provider-service-snol.onrender.com/"
      - key: ServiceUrls__ScheduleService
        value: "https://schedule-service-v1rl.onrender.com/"
      - key: ServiceUrls__AppointmentService
        value: "https://appointment-service-3khm.onrender.com/"
      - key: ServiceUrls__PaymentService
        value: "https://payment-service-bqmj.onrender.com/"
      - key: ServiceUrls__ReviewService
        value: "https://review-service-14o7.onrender.com/"
      - key: ServiceUrls__NotificationService
        value: "https://notification-service-o9q0.onrender.com/"
      - key: ServiceUrls__MedicalRecordService
        value: "https://medical-record-service.onrender.com/"
