services:
  - type: web
    name: auth-service
    env: docker
    plan: free
    rootDir: MediBook/services/auth-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: appointment-service
    env: docker
    plan: free
    rootDir: MediBook/services/appointment-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: medical-record-service
    env: docker
    plan: free
    rootDir: MediBook/services/medical-record-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: notification-service
    env: docker
    plan: free
    rootDir: MediBook/services/notification-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: payment-service
    env: docker
    plan: free
    rootDir: MediBook/services/payment-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: provider-service
    env: docker
    plan: free
    rootDir: MediBook/services/provider-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: review-service
    env: docker
    plan: free
    rootDir: MediBook/services/review-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: schedule-service
    env: docker
    plan: free
    rootDir: MediBook/services/schedule-service
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: api-gateway
    env: docker
    plan: free
    rootDir: MediBook/services/api-gateway
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d82nft50lvsc738kt0gg-a.ohio-postgres.render.com;Port=5432;Database=medibook_db_11eq;Username=medibook_user;Password=45n9ijVYboJaA9QrLoT92jCcRqvSgGaN;Pooling=true;TrustServerCertificate=true;"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJwtAuthenticationThatMustBeAtLeast32BytesLength!"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
