envVarGroups:
  - name: shared-config
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

services:
  - type: web
    name: auth-service
    env: docker
    plan: free
    rootDir: MediBook/services/auth-service
    envVarGroups:
      - shared-config

  - type: web
    name: appointment-service
    env: docker
    plan: free
    rootDir: MediBook/services/appointment-service
    envVarGroups:
      - shared-config

  - type: web
    name: medical-record-service
    env: docker
    plan: free
    rootDir: MediBook/services/medical-record-service
    envVarGroups:
      - shared-config

  - type: web
    name: notification-service
    env: docker
    plan: free
    rootDir: MediBook/services/notification-service
    envVarGroups:
      - shared-config

  - type: web
    name: payment-service
    env: docker
    plan: free
    rootDir: MediBook/services/payment-service
    envVarGroups:
      - shared-config

  - type: web
    name: provider-service
    env: docker
    plan: free
    rootDir: MediBook/services/provider-service
    envVarGroups:
      - shared-config

  - type: web
    name: review-service
    env: docker
    plan: free
    rootDir: MediBook/services/review-service
    envVarGroups:
      - shared-config

  - type: web
    name: schedule-service
    env: docker
    plan: free
    rootDir: MediBook/services/schedule-service
    envVarGroups:
      - shared-config

  - type: web
    name: api-gateway
    env: docker
    plan: free
    rootDir: MediBook/services/api-gateway
    envVarGroups:
      - shared-config
